### ISSUE TITLE
Request: Use Arc as Basetheme

### ISSUE THREAD

**Issue by porkslapchop** [PapirusDevelopmentTeam/papirus-gtk-theme#1]
I figured you could try to use the normal arc-theme as a base for Papirus and then change the colors to fit papirus and make the window buttons use either the default breeze theme or create assets similiar to the aurorae theme. Then if you change the kvantum theme similiar to the arc suite(in terms of style not color) it would looks incredibly uniform. Thoughts?

**Comment by porkslapchop** [comment]
I found an interesting tool which basically lets you recolor numix-themes easily. I made one which uses papirus-colors. [https://cloud.wyffy.com/index.php/s/rYDUVWgUCKy1vwa](url) 

The tool can be found here: [https://github.com/actionless/oomox](url)

**Comment by varlesh** [comment]
It's really not needed, because Qt5/Qt4-apps use Kavantum and GTK-apps Use Arc Dark GTK theme.  And Numix have other style/
PS: I don't know GTK - can't develop and support this on the future, sorry.

**Comment by varlesh** [comment]
Papirus - this mod Breeze, not Arc. You can compare styles with Arc Dark KDE. I need remake all elements, it's not good variant. Also many peolpe like Papirus and i can't change this style.
